-- 1. Smazat starou tabulku (nebo user_certificates, pokud existovala)
DROP TABLE IF EXISTS certificates;
DROP TABLE IF EXISTS user_certificates;

-- 2. Vytvořit novou strukturu certificates
CREATE TABLE certificates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id TEXT NOT NULL,
  template_id BIGINT REFERENCES certificate_templates(id) ON DELETE CASCADE,
  master_id TEXT,         -- ID mistra, ke kterému se odznak/certifikát vztahuje (pro scope=PER_MASTER nebo ItemType=CERTIFICATE)
  title TEXT,
  item_type TEXT,         -- 'BADGE', 'CERTIFICATE'
  scope TEXT,             -- 'GLOBAL', 'PER_MASTER'
  points INTEGER DEFAULT 0,
  requirement TEXT,
  locked BOOLEAN DEFAULT true,
  earned_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_certificates_user ON certificates(user_id);
CREATE INDEX idx_certificates_master ON certificates(master_id);
